name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download GLuaLint
      run: curl -o glualint.zip -L https://github.com/FPtje/GLuaFixer/releases/download/$GLUALINT_VERSION/glualint-$GLUALINT_VERSION-linux.zip
      env:
        GLUALINT_VERSION: 1.21.0
    - name: Unzip GLuaLint
      run: unzip glualint.zip
    - name: Lint lua files
      run: ./glualint lua
